name: build & lint checking pipeline
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: build prod
        run: npm run build:prod
      - name: lint checked
        run: npm run lint:check
